"""Document retrieval interface (A17 incremental RAG).

Loads latest emitted lightweight keyword index artifacts if present under
``artifacts/retrieval`` generated by ``scripts/rag_ingest.py``.

Provides a ``retrieve_context`` function returning top-k chunks with optional
explanation metadata (matched tokens, overlap, coverage) governed by:
    - Env flags: NEURON_RETRIEVAL_DOCS_ENABLED, NEURON_RETRIEVAL_EXPLANATIONS_ENABLED
    - Runtime param: retrieval.enable_explanations

If no index artifacts are present or feature disabled, returns empty list.
Safe failure path avoids raising to keep upstream agents resilient.
"""
from __future__ import annotations

from typing import List, Dict, Any, Tuple, Optional
import json, pathlib, re, math, os, sqlite3, hashlib, time as _time
try:
    from rag.window import optimize_window  # type: ignore
except Exception:  # pragma: no cover
    optimize_window = None  # type: ignore
try:
    from core.metrics import RETRIEVAL_WINDOW_COVERAGE_RATIO  # type: ignore
except Exception:  # pragma: no cover
    RETRIEVAL_WINDOW_COVERAGE_RATIO = None  # type: ignore

from config import flags as _flags_mod  # type: ignore
try:  # runtime params optional during early boot
    from config import runtime_params  # type: ignore
except Exception:  # pragma: no cover
    runtime_params = None  # type: ignore

_TOKEN_RE = re.compile(r"[A-Za-z0-9_\-]+")

_INDEX_CACHE: Dict[str, List[Tuple[str, int]]] | None = None
_MANIFEST_CACHE: List[Dict[str, Any]] | None = None
_CHUNK_TEXT_CACHE: Dict[Tuple[str,int], str] | None = None
_RERANK_MODEL = None  # lazy loaded cross-encoder (optional)
_CORRECTIVE_HISTORY: List[Dict[str, Any]] = []  # recent corrective iterations
_RETRIEVAL_METRICS: Dict[str, Any] = {
    "last": None,
    "history": [],  # list of {ts, query_hash, top_docs}
    "topk_drift": 0.0,
    "avg_overlap_precision": None,
}

# Lightweight SQLite persistence path for retrieval_chunks (optional)
_SQLITE_PATH = os.getenv("SQLITE_DB_PATH", "artifacts/neuron.db")
def _active_tenant_id() -> str | None:
    """Placeholder for active tenant context (to be wired via middleware)."""
    try:
        # Runtime param override (testing) retrieval.tenant.override
        if runtime_params is not None:
            tv = runtime_params.get_param("tenant.override")
            if tv:
                return str(tv)
    except Exception:
        pass
    return None


def _persist_chunk(doc: str, chunk_id: int, text: str | None):  # best-effort, silent failures
    try:
        if not _SQLITE_PATH:
            return
        pathlib.Path(_SQLITE_PATH).parent.mkdir(parents=True, exist_ok=True)
        conn = sqlite3.connect(_SQLITE_PATH)
        conn.execute("CREATE TABLE IF NOT EXISTS retrieval_chunks (id TEXT PRIMARY KEY, doc TEXT, chunk_id INT, hash TEXT, text TEXT, length INT, tenant_id TEXT, created_ts REAL)")
        h = hashlib.sha256(f"{doc}:{chunk_id}:{text or ''}".encode()).hexdigest()[:32]
        pk = f"{doc}:{chunk_id}:{h}"
        tenant_id = _active_tenant_id()
        conn.execute("INSERT OR IGNORE INTO retrieval_chunks (id, doc, chunk_id, hash, text, length, tenant_id, created_ts) VALUES (?,?,?,?,?,?,?,?)",
                     (pk, doc, int(chunk_id), h, text, len(text or ''), tenant_id, _time.time()))
        conn.commit(); conn.close()
    except Exception:
        pass


def _load_latest_index() -> None:
    global _INDEX_CACHE, _MANIFEST_CACHE, _CHUNK_TEXT_CACHE
    if _INDEX_CACHE is not None:
        return
    try:
        base = pathlib.Path("artifacts/retrieval")
        if not base.exists():
            _INDEX_CACHE = {}
            _MANIFEST_CACHE = []
            _CHUNK_TEXT_CACHE = {}
            return
        index_files = sorted(base.glob("index_*.json"))
        manifest_files = sorted(base.glob("manifest_*.json"))
        if not index_files:
            _INDEX_CACHE = {}
            _MANIFEST_CACHE = []
            _CHUNK_TEXT_CACHE = {}
            return
        latest_index = index_files[-1]
        latest_manifest = manifest_files[-1] if manifest_files else None
        _INDEX_CACHE = json.loads(latest_index.read_text(encoding="utf-8"))
        if latest_manifest:
            _MANIFEST_CACHE = json.loads(latest_manifest.read_text(encoding="utf-8"))
        else:
            _MANIFEST_CACHE = []
        # Attempt to reconstruct chunk text by re-running lightweight ingestion for listed docs (best-effort)
        _CHUNK_TEXT_CACHE = {}
        try:
            docs = {m.get("doc") for m in (_MANIFEST_CACHE or []) if m.get("doc")}
            # Only load small docs (<= 200k each) to avoid heavy I/O
            for d in docs:
                p = pathlib.Path("docs")/str(d)
                if p.exists() and p.is_file() and p.stat().st_size <= 200_000:
                    text = p.read_text(encoding="utf-8", errors="ignore")
                    # Recreate chunking heuristics (approx) using defaults from rag_ingest
                    chunk_size = 800
                    overlap = 80
                    step = max(1, chunk_size - overlap)
                    for i, start in enumerate(range(0, len(text), step)):
                        chunk = text[start:start+chunk_size]
                        _CHUNK_TEXT_CACHE[(d, i)] = chunk
        except Exception:
            pass
    except Exception:  # pragma: no cover
        _INDEX_CACHE = {}
        _MANIFEST_CACHE = []
        _CHUNK_TEXT_CACHE = {}


def _tokenize(s: str) -> List[str]:
    return [t.lower() for t in _TOKEN_RE.findall(s)]


def _runtime_param_enabled(name: str, fallback: bool) -> bool:
    try:
        if runtime_params is None:
            return fallback
        val = runtime_params.get_param(name)
        return bool(val) if val is not None else fallback
    except Exception:  # pragma: no cover
        return fallback


def _maybe_load_reranker() -> Optional[Any]:  # type: ignore[override]
    global _RERANK_MODEL
    if _RERANK_MODEL is not None:
        return _RERANK_MODEL
    try:
        import time as _t
        start_load = _t.time()
        if runtime_params is not None:
            enabled = runtime_params.get_param("retrieval.rerank.enabled")
            if enabled not in {1, "1", True, "true"}:
                return None
        from sentence_transformers import CrossEncoder  # type: ignore
        model_name = "cross-encoder/ms-marco-MiniLM-L-6-v2"
        try:
            if runtime_params is not None:
                mn = runtime_params.get_param("retrieval.rerank.model")
                if mn:
                    model_name = str(mn)
        except Exception:
            pass
        _RERANK_MODEL = CrossEncoder(model_name)
        # Record load latency metric
        try:
            from core.metrics import RETRIEVAL_RERANK_MODEL_LOAD_LATENCY  # type: ignore
            RETRIEVAL_RERANK_MODEL_LOAD_LATENCY.set(_t.time() - start_load)
        except Exception:
            pass
        return _RERANK_MODEL
    except Exception:  # pragma: no cover
        _RERANK_MODEL = None
        return None


def retrieve_context(query: str, k: int = 5) -> List[Dict[str, Any]]:  # noqa: D401
    """Retrieve top-k document chunks for query.

    Supports two scoring modes via runtime param `retrieval.scoring.mode`:
      - keyword (default): score = raw token overlap count
      - hybrid: score = (1-w)*coverage + w*idf_coverage, where
            coverage     = overlap / |query_tokens|
            idf_coverage = sum(idf(t) for matched t)/sum(idf(t) for all query t)
            idf(t)       = 1 + ln(N / (1 + df(t)))
            w            = retrieval.hybrid.embedding_weight (0..1 clamp)

    Explanation (when enabled) augments with: overlap, coverage, idf_coverage, composite, embedding_weight.
    Falls back gracefully to keyword-only if IDF cannot be computed.
    Returns list of dicts with keys: doc, chunk_id, score, (optional) explanation. Empty list on disable or absence.
    """
    # flags() previously imported incorrectly leading to attribute error in tests.
    try:
        f = _flags_mod.flags()
    except Exception:
        f = {}
    if not f.get("RETRIEVAL_DOCS_ENABLED"):
        return []
    _load_latest_index()
    if not _INDEX_CACHE:
        return []
    q_tokens = set(_tokenize(query))
    if not q_tokens:
        return []
    scores: Dict[Tuple[str,int], int] = {}
    matched: Dict[Tuple[str,int], List[str]] = {}
    for qt in q_tokens:
        postings = _INDEX_CACHE.get(qt, [])  # type: ignore[index]
        for doc, cid in postings:
            key = (doc, cid)
            scores[key] = scores.get(key, 0) + 1
            matched.setdefault(key, []).append(qt)

    mode = "keyword"
    weight = 0.0
    try:
        if runtime_params is not None:
            mode = str(runtime_params.get_param("retrieval.scoring.mode") or "keyword")
            weight = float(runtime_params.get_param("retrieval.hybrid.embedding_weight") or 0.3)
    except Exception:
        pass
    weight = max(0.0, min(1.0, weight))

    # Compute IDF if hybrid
    idf: Dict[str, float] = {}
    if mode == "hybrid":
        try:
            seen_pairs = set()
            for postings in _INDEX_CACHE.values():  # type: ignore[union-attr]
                for doc, cid in postings:
                    seen_pairs.add((doc, cid))
            N = max(1, len(seen_pairs))
            for tok, postings in _INDEX_CACHE.items():  # type: ignore[union-attr]
                df = len({(d, c) for (d, c) in postings})
                idf[tok] = 1.0 + math.log(N / (1 + df))
        except Exception:  # pragma: no cover
            idf = {}
            mode = "keyword"  # degrade gracefully

    ranked = sorted(scores.items(), key=lambda x: x[1], reverse=True)[:k*10]
    explanations_allowed = f.get("RETRIEVAL_EXPLANATIONS_ENABLED") and _runtime_param_enabled("retrieval.enable_explanations", False)

    if mode == "hybrid" and idf:
        query_idf_total = sum(idf.get(t, 0.0) for t in q_tokens) or 1.0
    else:
        query_idf_total = 1.0

    entries: List[Tuple[float, Dict[str, Any], int]] = []
    for (doc, cid), overlap in ranked:
        coverage = overlap / max(1, len(q_tokens))
        if mode == "hybrid" and idf:
            toks = matched.get((doc, cid), [])
            idf_cov = sum(idf.get(t, 0.0) for t in toks) / query_idf_total
            composite = (1 - weight) * coverage + weight * idf_cov
            score_val = composite
        else:
            idf_cov = None
            composite = None
            score_val = overlap
        rec: Dict[str, Any] = {"doc": doc, "chunk_id": cid, "score": score_val}
        if explanations_allowed:
            toks = matched.get((doc, cid), [])
            prov_hash = None
            for m in (_MANIFEST_CACHE or []):
                if m.get("doc") == doc and m.get("chunk_id") == cid:
                    prov_hash = m.get("hash")
                    break
            exp: Dict[str, Any] = {"matched_tokens": toks, "overlap": overlap, "coverage": coverage, "provenance_hash": prov_hash}
            if mode == "hybrid" and idf_cov is not None:
                exp.update({
                    "idf_coverage": idf_cov,
                    "embedding_weight": weight,
                    "composite": composite,
                    "scoring_mode": mode,
                })
            rec["explanation"] = exp
        entries.append((score_val, rec, overlap))

    # Sort by score then raw overlap as secondary
    entries.sort(key=lambda x: (x[0], x[2]), reverse=True)
    ranked_entries = entries[:k*2]  # widen for optimizer
    out = [r for _s, r, _ov in ranked_entries]

    # Optional cross-encoder re-ranking (Phase A)
    try:
        rr_top = None
        if runtime_params is not None:
            rr_top = runtime_params.get_param("retrieval.rerank.top_n")
        rr_top_n = int(rr_top or 50)
    except Exception:
        rr_top_n = 50
    try:
        rerank_model = _maybe_load_reranker()
        if rerank_model and out:
            # Build candidate text pairs: (query, doc#chunk_id) OR doc content placeholder (manifest lacks full text)
            # Since we only have doc id & chunk id, attempt to reconstruct pseudo text from matched tokens for now.
            pairs = []
            for rec in out[:rr_top_n]:
                exp = rec.get("explanation") or {}
                toks = exp.get("matched_tokens") or []
                pseudo = " ".join(toks)
                pairs.append([query, pseudo])
            if pairs:
                scores_rr = rerank_model.predict(pairs)
                for rec, sc in zip(out[:len(scores_rr)], scores_rr):
                    rec["rerank_score"] = float(sc)
                out.sort(key=lambda r: r.get("rerank_score", r.get("score", 0.0)), reverse=True)
    except Exception:  # pragma: no cover
        pass

    # Optional window optimization (Batch 20)
    optimize_enabled = _runtime_param_enabled("retrieval.window.optimize", False)
    if optimize_enabled and optimize_window and ranked_entries:
        token_budget = None
        try:
            if runtime_params is not None:
                token_budget = int(runtime_params.get_param("retrieval.window.token_budget") or 0)
        except Exception:
            token_budget = None
        # Build candidate list with matched tokens if explanations present
        candidates = []
        for _s, rec, _ov in ranked_entries:
            exp = rec.get("explanation") or {}
            toks = exp.get("matched_tokens") or []
            key = (rec.get("doc"), rec.get("chunk_id"))
            candidates.append({"key": key, "tokens": toks, "score": rec.get("score")})
        try:
            selected_keys, coverage, _covered = optimize_window(candidates, token_budget=token_budget)
            if RETRIEVAL_WINDOW_COVERAGE_RATIO is not None:
                try:
                    RETRIEVAL_WINDOW_COVERAGE_RATIO.set(coverage)
                except Exception:
                    pass
            filtered = []
            for rec in out:
                key = (rec.get("doc"), rec.get("chunk_id"))
                if key in selected_keys:
                    filtered.append(rec)
            # Preserve original ordering of filtered subset
            out = filtered
        except Exception:
            pass
    else:
        out = out[:k]
    # Persist chunk metadata (optionally including reconstructed text) for hunting/time filters
    try:
        persist_text = False
        if runtime_params is not None:
            pv = runtime_params.get_param("retrieval.persist_text")
            persist_text = pv in {1, '1', True, 'true'}
        for rec in out:
            doc = rec.get("doc")
            cid = int(rec.get("chunk_id"))
            text = None
            if persist_text and _CHUNK_TEXT_CACHE is not None:
                text = _CHUNK_TEXT_CACHE.get((doc, cid))
            _persist_chunk(doc, cid, text)
    except Exception:
        pass
    # --- Metrics: overlap precision proxy & top-k drift ---
    try:
        import time as _t, hashlib as _h
        ts = _t.time()
        # Overlap precision proxy: average matched token coverage among returned items
        coverages = []
        for rec in out:
            exp = rec.get("explanation") or {}
            cov = exp.get("coverage")
            if isinstance(cov, (int,float)):
                coverages.append(cov)
        if coverages:
            avg_cov = sum(coverages)/len(coverages)
        else:
            avg_cov = None
        # Top-k drift: Jaccard distance vs previous top-k doc set
        doc_keys = {f"{r.get('doc')}#{r.get('chunk_id')}" for r in out[:k]}
        prev = _RETRIEVAL_METRICS.get('last') or {}
        prev_keys = set(prev.get('top_docs') or [])
        drift = 0.0
        if prev_keys:
            inter = len(doc_keys & prev_keys)
            union = len(doc_keys | prev_keys) or 1
            jaccard = inter/union
            drift = 1 - jaccard
        # Update history (bounded)
        entry = {
            "ts": ts,
            "query_hash": _h.sha256(query.encode()).hexdigest()[:16],
            "top_docs": list(doc_keys),
            "avg_coverage": avg_cov,
            "drift": drift,
        }
        _RETRIEVAL_METRICS['last'] = entry
        hist = _RETRIEVAL_METRICS.get('history') or []
        hist.append(entry)
        if len(hist) > 200:
            hist = hist[-200:]
        _RETRIEVAL_METRICS['history'] = hist
        # Rolling average coverage
        cov_vals = [h.get('avg_coverage') for h in hist if isinstance(h.get('avg_coverage'), (int,float))]
        if cov_vals:
            _RETRIEVAL_METRICS['avg_overlap_precision'] = sum(cov_vals)/len(cov_vals)
        _RETRIEVAL_METRICS['topk_drift'] = drift
        # Emit Prometheus gauges (runtime param gating)
        try:
            emit_enabled = True
            if runtime_params is not None:
                v = runtime_params.get_param('retrieval.metrics.enable')
                if v is not None:
                    emit_enabled = v in {1,'1',True,'true'}
            if emit_enabled:
                from core.metrics import RETRIEVAL_OVERLAP_PRECISION, RETRIEVAL_TOPK_DRIFT  # type: ignore
                try:
                    if _RETRIEVAL_METRICS.get('avg_overlap_precision') is not None:
                        RETRIEVAL_OVERLAP_PRECISION.set(_RETRIEVAL_METRICS['avg_overlap_precision'])
                    RETRIEVAL_TOPK_DRIFT.set(drift)
                except Exception:
                    pass
        except Exception:
            pass
    except Exception:
        pass
    # Grounding spans (Phase A): attach placeholder span indices referencing pseudo tokens list
    try:
        grounding_enabled = False
        if runtime_params is not None:
            g = runtime_params.get_param("retrieval.grounding.enabled")
            grounding_enabled = g in {1, "1", True, "true"}
        if grounding_enabled:
            for rec in out:
                doc = rec.get("doc")
                cid = rec.get("chunk_id")
                text = None
                if _CHUNK_TEXT_CACHE is not None:
                    text = _CHUNK_TEXT_CACHE.get((doc, cid))
                exp = rec.get("explanation") or {}
                toks = exp.get("matched_tokens") or []
                spans = []
                if text:
                    lower_text = text.lower()
                    for t in toks:
                        t_l = t.lower()
                        # naive first occurrence search (later: multi-span match)
                        idx = lower_text.find(t_l)
                        if idx >= 0:
                            spans.append({"start": idx, "end": idx + len(t_l), "token": t})
                else:
                    # Fallback pseudo sequential spans
                    pos = 0
                    for t in toks:
                        l = len(t)
                        spans.append({"start": pos, "end": pos + l, "token": t})
                        pos += l + 1
                if spans:
                    rec["grounding"] = {"doc": doc, "chunk_id": cid, "spans": spans, "approx": text is None}
    except Exception:
        pass
    return out


# --- Phase B: Corrective RAG Loop (scaffold) ---
def _critic_detect_unsupported(answer: str, context_records: List[Dict[str, Any]]) -> Dict[str, Any]:
    """Heuristic critic: detect CVE IDs or numbers not grounded in matched tokens.

    Returns dict with counts and unsupported token list. Purely string-based placeholder.
    """
    try:
        import re
        cve_pattern = re.compile(r"CVE-\d{4}-\d{4,7}", re.IGNORECASE)
        nums_pattern = re.compile(r"\b\d+\b")
        answer_lc = answer.lower()
        grounded_tokens = set()
        for rec in context_records:
            exp = rec.get("explanation") or {}
            for t in exp.get("matched_tokens") or []:
                grounded_tokens.add(str(t).lower())
        unsupported: List[str] = []
        for cve in cve_pattern.findall(answer):
            if cve.lower() not in grounded_tokens:
                unsupported.append(cve)
        for num in nums_pattern.findall(answer):
            if num.lower() not in grounded_tokens:
                unsupported.append(num)
        return {"unsupported": unsupported, "unsupported_count": len(unsupported)}
    except Exception:  # pragma: no cover
        return {"unsupported": [], "unsupported_count": 0}


def corrective_refine(query: str, draft_answer: str, k: int = 5, threshold: int = 2) -> Dict[str, Any]:
    """Run one corrective refinement iteration.

    If unsupported token count >= threshold, expands query with simple synonyms (placeholder) and re-retrieves.
    Records metrics via RETRIEVAL_CORRECTIVE_ITERATIONS_TOTAL / RETRIEVAL_CORRECTIVE_ACCEPT_RATIO.
    Returns dict with fields: refined(bool), unsupported_count, added_terms, context(list).
    """
    try:
        from core.metrics import RETRIEVAL_CORRECTIVE_ITERATIONS_TOTAL, RETRIEVAL_CORRECTIVE_ACCEPT_RATIO  # type: ignore
    except Exception:  # pragma: no cover
        RETRIEVAL_CORRECTIVE_ITERATIONS_TOTAL = None  # type: ignore
        RETRIEVAL_CORRECTIVE_ACCEPT_RATIO = None  # type: ignore
    base_ctx = retrieve_context(query, k=k)
    critic = _critic_detect_unsupported(draft_answer, base_ctx)
    unsupported_count = critic.get("unsupported_count", 0)
    refined = False
    added_terms: List[str] = []
    final_ctx = base_ctx
    if unsupported_count >= threshold:
        # naive synonym expansion (placeholder)
        for tok in critic.get("unsupported", [])[:5]:
            if tok.lower().startswith("cve-"):
                added_terms.append(tok)
        if added_terms:
            refined_query = query + " " + " ".join(set(added_terms))
            final_ctx = retrieve_context(refined_query, k=k)
            refined = True
    # Update metrics
    try:
        if RETRIEVAL_CORRECTIVE_ITERATIONS_TOTAL is not None:
            outcome = "accepted" if refined else "skipped"
            RETRIEVAL_CORRECTIVE_ITERATIONS_TOTAL.labels(outcome=outcome).inc()
            # Maintain rolling acceptance ratio
            _CORRECTIVE_HISTORY.append(int(refined))
            if len(_CORRECTIVE_HISTORY) > 200:
                _CORRECTIVE_HISTORY.pop(0)
            if RETRIEVAL_CORRECTIVE_ACCEPT_RATIO is not None:
                if _CORRECTIVE_HISTORY:
                    RETRIEVAL_CORRECTIVE_ACCEPT_RATIO.set(sum(_CORRECTIVE_HISTORY)/len(_CORRECTIVE_HISTORY))
    except Exception:  # pragma: no cover
        pass
    result = {
        "refined": refined,
        "unsupported_count": unsupported_count,
        "added_terms": added_terms,
        "context": final_ctx,
    }
    return result

__all__ = ["retrieve_context", "_RETRIEVAL_METRICS", "corrective_refine"]


def run_corrective(query: str, initial_answer: str | None = None, k: int = 5) -> Dict[str, Any]:
    """Execute corrective refinement loop with acceptance controls.

    Acceptance params (runtime params with defaults):
      - retrieval.corrective.max_iterations (int, default 3)
      - retrieval.corrective.deadband_ratio (float, default 0.05)

    Deadband: if unsupported_count / max(1, tokens_in_answer) <= deadband_ratio after an iteration, stop early.
    Returns dict with: iterations, final_context, final_answer (placeholder: unchanged), history[{unsupported_count, refined}].
    """
    try:
        from core.metrics import (
            RETRIEVAL_CORRECTIVE_LAST_ITERATIONS,
            RETRIEVAL_CORRECTIVE_ITERATION_DURATION,
        )  # type: ignore
    except Exception:  # pragma: no cover
        RETRIEVAL_CORRECTIVE_LAST_ITERATIONS = None  # type: ignore
        RETRIEVAL_CORRECTIVE_ITERATION_DURATION = None  # type: ignore
    max_iter = 3
    deadband = 0.05
    try:
        if runtime_params is not None:
            mv = runtime_params.get_param("retrieval.corrective.max_iterations")
            dv = runtime_params.get_param("retrieval.corrective.deadband_ratio")
            if mv is not None:
                max_iter = max(1, int(mv))
            if dv is not None:
                deadband = max(0.0, float(dv))
    except Exception:
        pass
    answer = initial_answer or ""
    history: List[Dict[str, Any]] = []
    final_ctx: List[Dict[str, Any]] = []
    iterations = 0
    for i in range(max_iter):
        import time as _t
        t0 = _t.time()
        # On first iteration if no answer we synthesize a placeholder using query tokens
        if not answer:
            answer = query
        result = corrective_refine(query, answer, k=k)
        iterations += 1
        unsupported = int(result.get("unsupported_count", 0))
        tokens_in_answer = len(answer.split())
        ratio = unsupported / max(1, tokens_in_answer)
        history.append({
            "iteration": i+1,
            "unsupported_count": unsupported,
            "ratio": ratio,
            "refined": bool(result.get("refined")),
        })
        final_ctx = result.get("context") or final_ctx
        if RETRIEVAL_CORRECTIVE_ITERATION_DURATION is not None:
            try:
                RETRIEVAL_CORRECTIVE_ITERATION_DURATION.observe(_t.time() - t0)
            except Exception:
                pass
        if ratio <= deadband:
            break
        # If refined produced new context, optionally adjust answer (placeholder: keep original until generation layer added)
    if RETRIEVAL_CORRECTIVE_LAST_ITERATIONS is not None:
        try:
            RETRIEVAL_CORRECTIVE_LAST_ITERATIONS.set(iterations)
        except Exception:
            pass
    return {
        "iterations": iterations,
        "history": history,
        "final_context": final_ctx,
        "final_answer": answer,
        "deadband": deadband,
        "max_iterations": max_iter,
    }

__all__.append("run_corrective")
