"""Centralized detector default constants (Batch 5+)."""
from __future__ import annotations

# Lateral Movement Defaults
LATERAL_THRESHOLD_DEFAULT = 5
LATERAL_TTL_SECONDS_DEFAULT = 1800.0
LATERAL_MAX_USERS_DEFAULT = 5000

# Beaconing Defaults
BEACON_MIN_INTERVALS_DEFAULT = 5
BEACON_MAX_INTERVALS_DEFAULT = 12
BEACON_TTL_SECONDS_DEFAULT = 1800.0
BEACON_JITTER_RATIO_DEFAULT = 0.15
BEACON_MAX_AVG_INTERVAL_DEFAULT = 60.0
BEACON_MAX_FLOWS_DEFAULT = 20000

# DNS Tunneling Defaults
DNS_MIN_LABEL_LEN_DEFAULT = 30
DNS_MIN_UNIQUE_RATIO_DEFAULT = 0.6

# Persistence Defaults
PERSISTENCE_PARENTS_DEFAULT = ["powershell.exe", "cmd.exe", "bash"]
PERSISTENCE_TARGETS_DEFAULT = ["reg.exe", "schtasks.exe", "launchctl", "systemctl"]

__all__ = [
    'LATERAL_THRESHOLD_DEFAULT','LATERAL_TTL_SECONDS_DEFAULT','LATERAL_MAX_USERS_DEFAULT',
    'BEACON_MIN_INTERVALS_DEFAULT','BEACON_MAX_INTERVALS_DEFAULT','BEACON_TTL_SECONDS_DEFAULT','BEACON_JITTER_RATIO_DEFAULT','BEACON_MAX_AVG_INTERVAL_DEFAULT','BEACON_MAX_FLOWS_DEFAULT',
    'DNS_MIN_LABEL_LEN_DEFAULT','DNS_MIN_UNIQUE_RATIO_DEFAULT',
    'PERSISTENCE_PARENTS_DEFAULT','PERSISTENCE_TARGETS_DEFAULT'
]
